---

- name: Pull down latest git code
  git: repo={{ git_repo }}
       dest={{ project_path }}
       accept_hostkey=yes
       version={{ git_version }}
  tags: git

- name: ensure user ownds project
  file: path={{ project_path }}
        owner=ubuntu
        group=ubuntu

